#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/8/22 21:51
# @Author  : baob
# @Site    : 
# @File    : getwordtext.py
# @Software: PyCharm Community Edition


# 读取docx中的文本代码示例
import docx
from docx import Document
import pandas as pd

data_dic = {}
column_txts = []

path = r'D:\Study\456.docx'  # 文件路径
document = Document(path)  # 读入文件
tables = document.tables  # 获取文件中的表格集
table = tables[1]  # 获取文件中的第一个表格


# 获取收入列数据
for i in range(1, (len(table.rows))):  # 从表格第一行开始循环读取表格数据
    # 格式化金额
    result = str(table.cell(i, 3).text).strip().replace("￥", "")
    column_txts.append(result)

print(column_txts)
# 计算收入总金额
price_sum = 0
for i in column_txts:
    fmt_int_i = float(i)
    price_sum += fmt_int_i
print(price_sum)


# 读取任务项
def get_task():
    task_lst = []
    for i in range(1, (len(table.rows))):  # 从表格第一行开始循环读取表格数据
        # 格式化金额
        result = str(table.cell(i, 0).text).strip()
        task_lst.append(result)
    return task_lst

data_dic["执行任务项"]=get_task()
data_dic["收入"]=column_txts


if __name__ == "__main__":
    df = pd.DataFrame(data_dic)
    df = df.set_index("执行任务项")
    df.to_excel(r'D:\Study\11.xlsx')
